language: objective-c
osx_image: xcode11
xcode_project: TravisCIDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCIDemo
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8

before_install:
- gem install fir-cli
after_deploy:
- fir p app/build/outputs/apk/app-release.apk -T 938f564500c3337a9c0037972e924acc -c "`git cat-file tag $TRAVIS_TAG`"
