language: objective-c
osx_image: xcode11
xcode_project: TravisCIDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCIDemo
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8
