language: objective-c
osx_image: xcode11
xcode_project: TravisCIDemo.xcodeproj # path to your xcodeproj folder
xcode_scheme: TravisCIDemo
xcode_destination: platform=iOS Simulator,OS=13.0,name=iPhone 8
#before_install:
#- gem install bundler
#- gem install fir-cli
#- fir version
#after_deploy:
#curl -X "POST" "http://api.fir.im/apps" \ 
 #    -H "Content-Type: application/json" \
  #   -d "{\"type\":\"ios\", \"bundle_id\":\"com.bigone.TravisCIDemo\", \"api_token\":\"938f564500c3337a9c0037972e924acc\"}"


#- fir p Build/Products/Debug-iphonesimulator/TravisCIDemo.app -T 938f564500c3337a9c0037972e924acc -c "`git cat-file tag $TRAVIS_TAG`"
